CREATE or replace TRIGGER zaktualizuj_wolne_miejsca
  AFTER INSERT ON REZERWACJE
  FOR EACH ROW
  BEGIN
    UPDATE WYCIECZKI
      SET LICZBA_WOLNYCH_MIEJSC = WYCIECZKI.LICZBA_WOLNYCH_MIEJSC -1
    WHERE ID_WYCIECZKI = :NEW.ID_WYCIECZKI;
  END zaktualizuj_wolne_miejsca;