CREATE OR REPLACE TRIGGER wolne_miejsca_zmiana_liczby_miejsc
  BEFORE UPDATE OF LICZBA_MIEJSC ON WYCIECZKI
    FOR EACH ROW
  BEGIN
    if :NEW.LICZBA_MIEJSC < (:OLD.LICZBA_MIEJSC - :OLD.LICZBA_WOLNYCH_MIEJSC)
      THEN
      RAISE_APPLICATION_ERROR(-123, 'Too many reservations');
      ROLLBACK;
    ELSE
      UPDATE WYCIECZKI w
        set w.LICZBA_WOLNYCH_MIEJSC = :NEW.LICZBA_MIEJSC - :OLD.LICZBA_WOLNYCH_MIEJSC
        WHERE w.ID_WYCIECZKI = :NEW.ID_WYCIECZKI;
    END IF;
  END wolne_miejsca_zmiana_liczby_miejsc;